$ErrorActionPreference = "Continue"
$env:GIT_PAGER = "cat"
Set-Location "C:\Users\abuel\Documents\trae_projects\ERB_VitaSlims"

if (Test-Path ".git/index.lock") { Remove-Item ".git/index.lock" -Force }
if (Test-Path "push_v3.74.584.ps1") { Remove-Item -LiteralPath "push_v3.74.584.ps1" -Force }

$v = Get-Content -LiteralPath "lib/version.ts" -Raw
if ($v -match 'APP_VERSION = "3.74.585"') {
    Write-Host "+ 3.74.585" -ForegroundColor Green
} else { Write-Host "X version mismatch" -ForegroundColor Red; exit 1 }

if (-not (Test-Path "supabase/migrations/20260709000585_v3_74_585_bonus_orphan_cleanup_and_guard.sql")) {
    Write-Host "X migration mirror missing" -ForegroundColor Red; exit 1
}
Write-Host "+ bonus-orphan cleanup + guard migration mirrored" -ForegroundColor Green

Write-Host "Running tsc..." -ForegroundColor Cyan
$tsc = & npx tsc --noEmit -p tsconfig.json 2>&1
$tscErr = ($tsc | Select-String -Pattern "error TS").Count
if ($tscErr -eq 0) {
    Write-Host "+ 0 TS errors" -ForegroundColor Green
} else {
    Write-Host "X $tscErr TS errors" -ForegroundColor Red
    $tsc | Select-String -Pattern "error TS" | Select-Object -First 30 | ForEach-Object { Write-Host $_ }
    exit 1
}

# ⚠️ الشجرة بها آلاف ملفات ضجيج نهايات أسطر — الرفع انتقائى حصراً
git add -- `
    "supabase/migrations/20260709000585_v3_74_585_bonus_orphan_cleanup_and_guard.sql" `
    "lib/version.ts" `
    "push_v3.74.585.ps1" 2>&1 | Out-Null
git add -u -- "push_v3.74.584.ps1" 2>$null
git --no-pager diff --cached --stat
$staged = git diff --cached --name-only
if (-not $staged) {
    Write-Host "Nothing to commit" -ForegroundColor Yellow
} else {
    $msgPath = Join-Path $env:TEMP "commit_v3_74_585.txt"
    $msgLines = @(
        'fix(bonuses): v3.74.585 - orphan test bonus cleanup + auto-reversal guard',
        '',
        'Dashboard integrity scan flagged a sales bonus referencing a',
        'non-existent invoice: the 50 EGP pending commission generated by',
        'completing test booking BKG-2026-00001, whose whole chain was',
        'hard-deleted in the owner-ordered cleanup - user_bonuses was the',
        'one table that cleanup missed. Bonus was unpaid, outside any',
        'payroll run, zero accounting impact -> hard-deleted.',
        '',
        'Prevention (DB, live via MCP): BEFORE DELETE triggers on',
        'invoices and bookings auto-reverse UNPAID pending bonuses',
        '(status=reversed + reversed_at + Arabic reason). PAID bonuses',
        'are deliberately left flagged - a paid commission whose source',
        'document vanished must keep alerting until resolved via payroll',
        'correction.',
        '',
        'Verified: ic_bonus_invoice_orphan() now returns clean.'
    )
    Set-Content -LiteralPath $msgPath -Value $msgLines -Encoding UTF8
    git commit -F $msgPath 2>&1 | ForEach-Object { Write-Host $_ }
    Remove-Item -LiteralPath $msgPath -Force -ErrorAction SilentlyContinue
}

git push origin main 2>&1 | ForEach-Object { Write-Host $_ }
if ($LASTEXITCODE -eq 0) {
    Write-Host "`n+ v3.74.585 pushed - bonus integrity guard live" -ForegroundColor Green
}
