import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import { resolve } from 'path';

// Load .env.local
dotenv.config({ path: resolve(process.cwd(), '.env.local') });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || '';

if (!supabaseUrl || !supabaseKey) {
  console.error("Missing Supabase credentials in .env.local");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey, {
  auth: {
    autoRefreshToken: false,
    persistSession: false
  }
});

async function main() {
  console.log("Searching for test companies...");
  const { data: companies, error: companiesError } = await supabase
    .from('companies')
    .select('id, name')
    .ilike('name', '%تست%');

  if (companiesError) {
    console.error("Error finding companies:", companiesError);
    return;
  }

  if (!companies || companies.length === 0) {
    console.log("No test companies found matching '%تست%'.");
    return;
  }

  console.log("Found test companies:", companies.map(c => c.name).join(', '));
  const companyIds = companies.map(c => c.id);

  try {
    for (const companyId of companyIds) {
      console.log(`\nDeleting data for company: ${companyId}`);

      // Wait, we need to gather standard references to delete.
      // Easiest is to delete Invoices and Sales Orders. 
      // But they're linked to inventory_transactions, third_party_inventory, journal_entries, etc.
      // Some DBs have ON DELETE CASCADE so deleting sales_orders deletes invoices, items, and allocations.
      // Wait, journal entries generated by these invoices.

      // 1. Get Invoices for the company
      const { data: invoices } = await supabase
        .from('invoices')
        .select('id, type')
        .eq('company_id', companyId);

      const invoiceIds = invoices?.map(i => i.id) || [];
      if (invoiceIds.length > 0) {
        console.log(`Found ${invoiceIds.length} invoices. Deleting related records...`);
        
        // Deleting from third_party_inventory (where reference_id is invoice_id and reference_type is 'invoice')
        const { error: tpiError } = await supabase
          .from('third_party_inventory')
          .delete()
          .in('reference_id', invoiceIds);
        if (tpiError) console.error("Error deleting third party inventory:", tpiError);

        // Third party inventory might also use sales_order_id, wait, reference_type = 'sales_delivery'
        // let's just delete ALL third_party_inventory for this company for now since we're wiping test data
        
        // Similarly for journal_entries
        const { error: jeError } = await supabase
          .from('journal_entries')
          .delete()
          .in('reference_id', invoiceIds);
        if (jeError) console.error("Error deleting journal entries:", jeError);
        
        // Delete invoices
        const { error: invDeleteError } = await supabase
          .from('invoices')
          .delete()
          .in('id', invoiceIds);
        if (invDeleteError) console.error("Error deleting Invoices:", invDeleteError);
        else console.log("Deleted Invoices.");
      }

      // 2. Get Sales Orders
      const { data: salesOrders } = await supabase
        .from('sales_orders')
        .select('id')
        .eq('company_id', companyId);

      const orderIds = salesOrders?.map(so => so.id) || [];
      if (orderIds.length > 0) {
        console.log(`Found ${orderIds.length} sales orders. Deleting related records...`);

        // Delete from third_party_inventory linked to Sales Orders
        const { error: tpiSoError } = await supabase
          .from('third_party_inventory')
          .delete()
          .in('reference_id', orderIds);
        
        // Delete related inventory_transactions (where document_id = sales_order_id. Wait, document_id might be invoice_id)
        // Actually inventory_transactions might be deleted by CASCADE. Let's see.

        // Delete sales orders
        const { error: soDeleteError } = await supabase
          .from('sales_orders')
          .delete()
          .in('id', orderIds);
        if (soDeleteError) console.error("Error deleting Sales Orders:", soDeleteError);
        else console.log("Deleted Sales Orders.");
      }

      // 3. To be absolutely sure, delete ALL third-party inventory records for the company
      const { error: tpiAllError } = await supabase
        .from('third_party_inventory')
        .delete()
        .eq('company_id', companyId);
      if (tpiAllError) console.error("Error deleting all third party inventory:", tpiAllError);
      else console.log("Deleted all third party inventory for company.");

      console.log("Cleanup finished for company", companyId);
    }
  } catch (err: any) {
    console.error("Execution failed:", err.message);
  }
}

main().catch(console.error);
