-- Seed additional page guides to cover all major application routes.
-- This brings total guide coverage from 21 to 36 page_key entries.
INSERT INTO public.page_guides (page_key, title_ar, title_en, description_ar, description_en, steps_ar, steps_en, tips_ar, tips_en)
VALUES
('sales_orders','طلبات المبيعات','Sales Orders','إنشاء وإدارة طلبات المبيعات قبل إصدار الفواتير النهائية. تُحوَّل لاحقاً إلى فواتير مبيعات.','Create and manage sales orders before issuing final invoices. Later converted to sales invoices.','["أنشئ طلب مبيعات جديداً مع تحديد العميل","أضف المنتجات والكميات والأسعار","أرسل الطلب للعميل للموافقة","بعد الموافقة: حوّل الطلب لفاتورة مبيعات","تتبع حالة الطلبات: مفتوح / مكتمل / ملغى"]','["Create a new sales order with customer selection","Add products, quantities, and prices","Send the order to the customer for approval","After approval: convert to a sales invoice","Track order status: open / completed / cancelled"]',ARRAY['طلب المبيعات لا يُنشئ قيوداً محاسبية — فقط الفاتورة تفعل','يمكن تحويل الطلب جزئياً لفاتورة'],ARRAY['Sales orders do not create accounting entries — only invoices do','Orders can be partially converted to invoices']),

('sales_returns','مرتجعات المبيعات','Sales Returns','تسجيل وإدارة المرتجعات من العملاء. تُنشئ قيوداً محاسبية تعكس الإيرادات وتُعيد المخزون.','Record and manage customer returns. Creates journal entries reversing revenue and restoring inventory.','["ابحث عن الفاتورة الأصلية المراد إرجاعها","حدد المنتجات والكميات المرتجعة","اختر سبب الإرجاع","اعتمد المرتجع لإنشاء القيود المحاسبية","تحقق من إعادة المخزون والخصم من الإيرادات"]','["Find the original invoice to return","Specify products and quantities returned","Select return reason","Approve the return to create journal entries","Verify inventory restored and revenue reduced"]',ARRAY['المرتجع يعكس COGS تلقائياً ويُعيد المخزون بالتكلفة الأصلية','صافي المبيعات في التقارير = المبيعات - المرتجعات'],ARRAY['Return automatically reverses COGS and restores inventory at original cost','Net sales in reports = Sales - Returns']),

('purchase_returns','مرتجعات المشتريات','Purchase Returns','تسجيل المرتجعات للموردين وتحديث المخزون والذمم الدائنة تلقائياً.','Record returns to suppliers with automatic inventory and payables updates.','["حدد فاتورة الشراء المراد إرجاعها","اختر المنتجات والكميات المرتجعة","اعتمد المرتجع لتحديث المخزون","يُخصم المبلغ من الذمم الدائنة للمورد"]','["Select the purchase bill to return","Choose products and quantities","Approve the return to update inventory","Amount is deducted from supplier payables"]',ARRAY['مرتجع الشراء يُخفض المخزون ويُخفض الذمم الدائنة','تأكد من وجود كمية كافية قبل الإرجاع'],ARRAY['Purchase return reduces inventory and reduces payables','Ensure sufficient quantity exists before returning']),

('inventory_transfers','تحويلات المخزون','Inventory Transfers','نقل البضاعة بين المخازن والفروع مع تتبع كامل للحركات.','Transfer goods between warehouses and branches with full movement tracking.','["أنشئ تحويل جديد وحدد المخزن المصدر والمستهدف","أضف المنتجات والكميات المراد تحويلها","راجع التفاصيل وأكّد التحويل","تحقق من تحديث أرصدة المخزنين"]','["Create a new transfer with source and target warehouse","Add products and quantities to transfer","Review details and confirm the transfer","Verify both warehouse balances updated correctly"]',ARRAY['التحويل لا يُنشئ قيوداً محاسبية (نقل داخلي)','تأكد من توفر الكمية في المخزن المصدر قبل التحويل'],ARRAY['Transfers do not create accounting entries (internal movement)','Ensure sufficient stock in source warehouse before transferring']),

('fixed_assets','الأصول الثابتة','Fixed Assets','إدارة الأصول الثابتة للشركة وجداول الإهلاك والتقارير المالية المرتبطة.','Manage company fixed assets, depreciation schedules, and related financial reports.','["أضف أصلاً ثابتاً جديداً مع بيانات الاقتناء","حدد طريقة الإهلاك: قسط ثابت / متناقص","راجع جدول الإهلاك الشهري","سجّل بيع أو إتلاف الأصل عند الحاجة","راجع تقرير قيمة الأصول الصافية"]','["Add a new fixed asset with acquisition details","Set depreciation method: straight-line / declining","Review the monthly depreciation schedule","Record sale or disposal of asset when needed","Review net asset value report"]',ARRAY['الإهلاك يُسجَّل تلقائياً كمصروف شهري','بيع الأصل يُنشئ قيد مكسب أو خسارة حسب القيمة الدفترية'],ARRAY['Depreciation is recorded automatically as a monthly expense','Asset sale creates a gain or loss entry based on book value']),

('branches','الفروع','Branches','إدارة فروع الشركة وربط المعاملات والتقارير بكل فرع.','Manage company branches and link transactions and reports to each branch.','["أضف فرعاً جديداً مع بياناته الأساسية","حدد المسؤول عن الفرع والموقع","اربط المستخدمين والمخازن بالفرع","راجع تقارير كل فرع منفصلاً"]','["Add a new branch with basic details","Set the branch manager and location","Link users and warehouses to the branch","Review reports for each branch separately"]',ARRAY['معظم التقارير تدعم التصفية حسب الفرع','يمكن تعيين صلاحيات مختلفة لكل فرع'],ARRAY['Most reports support filtering by branch','Different permissions can be assigned per branch']),

('warehouses','المخازن','Warehouses','إدارة مخازن الشركة وربطها بالفروع والمنتجات.','Manage company warehouses and link them to branches and products.','["أضف مخزناً جديداً مع موقعه","اربط المخزن بالفرع المناسب","راجع أرصدة المخزون لكل مخزن","استخدم تقرير المخزون للمتابعة الدورية"]','["Add a new warehouse with its location","Link the warehouse to the appropriate branch","Review inventory balances per warehouse","Use the inventory report for periodic monitoring"]',ARRAY['كل فاتورة شراء تحدد المخزن المستلِم','تحديد المخزن الصحيح ضروري لدقة أرصدة المخزون'],ARRAY['Each purchase bill specifies the receiving warehouse','Selecting the correct warehouse is essential for accurate inventory']),

('cost_centers','مراكز التكلفة','Cost Centers','تتبع التكاليف والإيرادات حسب مراكز تكلفة محددة لتحليل دقيق للربحية.','Track costs and revenues by specific cost centers for precise profitability analysis.','["أنشئ مراكز التكلفة للأقسام أو المشاريع","اربط القيود المحاسبية بمراكز التكلفة","راجع تقرير تحليل مراكز التكلفة","قارن أداء مراكز التكلفة المختلفة"]','["Create cost centers for departments or projects","Link journal entries to cost centers","Review the cost center analysis report","Compare performance across different cost centers"]',ARRAY['مركز التكلفة اختياري لكنه يُثري التحليل المالي','يمكن ربط الفواتير والمصروفات بمراكز تكلفة مختلفة'],ARRAY['Cost center is optional but enriches financial analysis','Invoices and expenses can be linked to different cost centers']),

('drawings','السحوبات الشخصية','Drawings','تسجيل سحوبات الملاك من أموال الشركة وتأثيرها على حقوق الملكية.','Record owner withdrawals from company funds and their impact on equity.','["أنشئ سحباً جديداً وحدد المبلغ","حدد الحساب المصدر (نقدي / بنكي)","اختر حساب السحوبات المناسب","اعتمد العملية لإنشاء القيد المحاسبي"]','["Create a new drawing and enter the amount","Specify the source account (cash / bank)","Select the appropriate drawings account","Approve to create the accounting entry"]',ARRAY['السحوبات تُخفض حقوق الملكية مباشرة','لا ينبغي الخلط بين السحوبات الشخصية ومصروفات الشركة'],ARRAY['Drawings reduce equity directly','Personal drawings should not be confused with company expenses']),

('estimates','عروض الأسعار','Estimates / Quotations','إنشاء وإرسال عروض أسعار للعملاء. تُحوَّل لاحقاً لطلبات مبيعات أو فواتير.','Create and send price quotations to customers. Later converted to sales orders or invoices.','["أنشئ عرض سعر جديد مع تحديد العميل","أضف المنتجات والكميات والأسعار المقترحة","أرسل العرض للعميل","عند القبول: حوّل لطلب مبيعات أو فاتورة مباشرة","تتبع حالة العروض: مفتوح / مقبول / مرفوض"]','["Create a new quotation with customer selection","Add products, quantities, and proposed prices","Send the quotation to the customer","On acceptance: convert to sales order or direct invoice","Track quotation status: open / accepted / rejected"]',ARRAY['عروض الأسعار لا تُنشئ قيوداً محاسبية','يمكن تحديد تاريخ انتهاء صلاحية للعرض'],ARRAY['Quotations do not create accounting entries','You can set an expiry date on the quotation']),

('vendor_credits','أرصدة الموردين الدائنة','Vendor Credits','تسجيل الأرصدة الدائنة من الموردين الناتجة عن مرتجعات أو دفعات زائدة.','Record credit balances from suppliers resulting from returns or overpayments.','["راجع الأرصدة الدائنة المتاحة لكل مورد","أنشئ رصيداً دائناً من مرتجع شراء أو دفعة زائدة","طبّق الرصيد الدائن على فاتورة مستقبلية","راجع كشف حساب المورد للتحقق من الرصيد"]','["Review available credit balances per supplier","Create a credit from a purchase return or overpayment","Apply the credit balance to a future invoice","Review supplier account statement to verify balance"]',ARRAY['الرصيد الدائن يُخفض الدفعة المستحقة للمورد','تأكد من تطبيق الأرصدة قبل نهاية الفترة المحاسبية'],ARRAY['Credit balance reduces the amount due to the supplier','Ensure credits are applied before end of accounting period']),

('customer_debit_notes','مذكرات خصم العملاء','Customer Debit Notes','إصدار مذكرات خصم للعملاء لتعديل الذمم أو فرض رسوم إضافية.','Issue debit notes to customers to adjust receivables or charge additional fees.','["أنشئ مذكرة خصم جديدة للعميل","حدد المبلغ وسبب الخصم","اربط المذكرة بالفاتورة الأصلية إن وجدت","اعتمد المذكرة لتحديث رصيد الذمم المدينة"]','["Create a new debit note for the customer","Enter the amount and reason for the debit","Link to the original invoice if applicable","Approve to update the receivables balance"]',ARRAY['مذكرة الخصم تزيد الرصيد المستحق على العميل','استخدمها للرسوم الإضافية أو التصحيحات'],ARRAY['Debit note increases the balance owed by the customer','Use for additional charges or corrections']),

('accounting_periods','الفترات المحاسبية','Accounting Periods','إدارة الفترات المحاسبية وإقفال الفترات المنتهية لمنع إدخال قيود فيها.','Manage accounting periods and close ended periods to prevent new entries.','["راجع الفترات المحاسبية الحالية والمنتهية","أقفل الفترة المنتهية لحمايتها من التعديلات","افتح فترة جديدة لبدء محاسبة فترة جديدة","تحقق أن جميع القيود مرحّلة قبل الإقفال"]','["Review current and ended accounting periods","Close the ended period to protect it from modifications","Open a new period to start a new accounting cycle","Verify all entries are posted before closing"]',ARRAY['إقفال الفترة يمنع إضافة أو تعديل أي قيد فيها','تأكد من مراجعة شاملة للبيانات قبل الإقفال'],ARRAY['Closing a period prevents adding or editing any entry in it','Ensure a thorough data review before closing']),

('reports','التقارير','Reports','مركز التقارير الشامل: تقارير المبيعات والمشتريات والمخزون والمالية والضريبية.','Comprehensive reports hub: sales, purchases, inventory, financial, and tax reports.','["اختر نوع التقرير من القائمة","حدد الفترة الزمنية ونطاق البيانات","طبّق الفلاتر المناسبة (فرع، مخزن، عميل...)","اعرض النتائج وصدّرها بصيغة PDF أو Excel"]','["Select the report type from the list","Set the date range and data scope","Apply relevant filters (branch, warehouse, customer...)","Display results and export as PDF or Excel"]',ARRAY['جميع التقارير المالية تعتمد على القيود المرحّلة من GL','بعض التقارير تتيح المقارنة بين فترتين زمنيتين'],ARRAY['All financial reports rely on posted GL entries','Some reports allow comparison between two time periods'])

ON CONFLICT (page_key) DO UPDATE SET
  title_ar = EXCLUDED.title_ar, title_en = EXCLUDED.title_en,
  description_ar = EXCLUDED.description_ar, description_en = EXCLUDED.description_en,
  steps_ar = EXCLUDED.steps_ar, steps_en = EXCLUDED.steps_en,
  tips_ar = EXCLUDED.tips_ar, tips_en = EXCLUDED.tips_en,
  updated_at = now();
