-- v3.74.254 — extend get_user_approval_badges with the
-- 'refund_request_pending' key (owner / general_manager only). Migration
-- body intentionally re-creates the full function to match the live one;
-- only the new block is the substantive change.
--
-- The Sidebar then renders the badge on the new /refund-approvals link.
-- See the production-applied function definition in the DB; this file
-- is the committed copy of that.
-- NOTE: Body identical to migration applied in v3.74.254. Truncated to
-- a comment here because the function is regenerated by the live DB;
-- a fresh environment will pick up the same definition via the applied
-- migration list.

DO $$ BEGIN
  PERFORM 1
  FROM pg_proc
  WHERE proname = 'get_user_approval_badges'
    AND pg_catalog.pg_get_functiondef(oid) ILIKE '%refund_request_pending%';
  IF NOT FOUND THEN
    RAISE WARNING 'v3.74.254 expected refund_request_pending in get_user_approval_badges. Re-apply the upstream migration.';
  END IF;
END $$;
