-- =============================================================================
-- Enterprise-Grade Atomic Payment Processing + Customer Credit Ledger
-- =============================================================================
-- 1. Fix prevent_duplicate_journal_entry_v2: allow multiple invoice_payment
--    entries per invoice (required for partially-paid invoices)
-- 2. customer_credit_ledger: formal credit-balance tracking (replaces ad-hoc fields)
-- 3. process_invoice_payment_atomic: single DB transaction wrapping
--    payment INSERT + AR/Revenue journal + invoice UPDATE
-- =============================================================================

-- =============================================================================
-- SECTION 1: Fix Duplicate Prevention Trigger
-- Allow multiple journal entries for payment types (one per payment event)
-- =============================================================================
CREATE OR REPLACE FUNCTION prevent_duplicate_journal_entry_v2()
RETURNS TRIGGER AS $$
DECLARE
  v_count INT;
BEGIN
  IF NEW.reference_type IS NULL OR NEW.reference_id IS NULL THEN
    RETURN NEW;
  END IF;

  -- Payment journals are naturally one-per-payment, not one-per-invoice.
  -- Multiple payments on the same invoice create multiple valid journals.
  IF NEW.reference_type IN ('invoice_payment', 'bill_payment') THEN
    RETURN NEW;
  END IF;

  SELECT COUNT(*)
    INTO v_count
    FROM public.journal_entries
   WHERE company_id     = NEW.company_id
     AND reference_type = NEW.reference_type
     AND reference_id   = NEW.reference_id
     AND (is_deleted IS NULL OR is_deleted = FALSE)
     AND deleted_at IS NULL;

  IF v_count > 0 THEN
    RAISE EXCEPTION
      'DUPLICATE_JOURNAL_VIOLATION: A journal entry with '
      'reference_type=[%] and reference_id=[%] already exists '
      'for company [%]. '
      'Duplicate accounting entries are not permitted. '
      'Use a reversal entry to correct an existing posted entry.',
      NEW.reference_type, NEW.reference_id, NEW.company_id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- SECTION 2: Customer Credit Ledger
-- Formal double-entry subledger for customer credit balances
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.customer_credit_ledger (
  id               UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  company_id       UUID        NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  customer_id      UUID        NOT NULL REFERENCES public.customers(id),
  source_type      TEXT        NOT NULL
                   CHECK (source_type IN (
                     'sales_return',    -- credit generated by a return
                     'overpayment',     -- credit generated by overpayment
                     'manual_credit',   -- manually issued credit
                     'credit_applied',  -- credit used on an invoice
                     'credit_expired'   -- credit written off / expired
                   )),
  source_id        UUID,                -- FK to sales_returns.id / payments.id / invoices.id
  journal_entry_id UUID        REFERENCES public.journal_entries(id),
  amount           NUMERIC(15,2) NOT NULL,  -- positive = credit granted; negative = credit consumed
  description      TEXT,
  created_by       UUID        REFERENCES auth.users(id),
  created_at       TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  CONSTRAINT ccl_amount_nonzero CHECK (amount <> 0)
);

CREATE INDEX IF NOT EXISTS idx_ccl_company_customer
  ON public.customer_credit_ledger (company_id, customer_id);
CREATE INDEX IF NOT EXISTS idx_ccl_source
  ON public.customer_credit_ledger (source_type, source_id);
CREATE INDEX IF NOT EXISTS idx_ccl_created_at
  ON public.customer_credit_ledger (company_id, created_at DESC);

COMMENT ON TABLE public.customer_credit_ledger IS
  'سجل الأستاذ للرصيد الدائن للعملاء. كل سطر يمثل حركة (منح أو استهلاك). '
  'الرصيد المتاح = SUM(amount) للعميل. يجب أن يكون لكل حركة قيد GL مقابل.';

-- Function: Get available credit balance for a customer (from ledger, not GL)
CREATE OR REPLACE FUNCTION public.get_customer_credit_balance(
  p_company_id  UUID,
  p_customer_id UUID
)
RETURNS NUMERIC
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT COALESCE(SUM(amount), 0)
  FROM public.customer_credit_ledger
  WHERE company_id  = p_company_id
    AND customer_id = p_customer_id;
$$;

-- Function: Apply credit to an invoice (atomic: ledger debit + GL journal)
CREATE OR REPLACE FUNCTION public.apply_customer_credit_to_invoice(
  p_company_id     UUID,
  p_customer_id    UUID,
  p_invoice_id     UUID,
  p_amount         NUMERIC,
  p_user_id        UUID DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_available_credit  NUMERIC;
  v_invoice           RECORD;
  v_ar_account_id     UUID;
  v_branch_id         UUID;
  v_journal_id        UUID;
  v_credit_ledger_id  UUID;
  v_apply_amount      NUMERIC;
BEGIN
  -- Get available credit
  v_available_credit := public.get_customer_credit_balance(p_company_id, p_customer_id);
  IF v_available_credit < 0.01 THEN
    RAISE EXCEPTION 'NO_CREDIT_AVAILABLE: Customer has no available credit balance';
  END IF;

  -- Lock invoice
  SELECT * INTO v_invoice
  FROM invoices
  WHERE id = p_invoice_id AND company_id = p_company_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'INVOICE_NOT_FOUND: Invoice % not found', p_invoice_id;
  END IF;

  -- Amount to apply = min(available credit, remaining invoice balance)
  v_apply_amount := LEAST(
    p_amount,
    v_available_credit,
    GREATEST(0, v_invoice.total_amount - COALESCE(v_invoice.paid_amount, 0) - COALESCE(v_invoice.returned_amount, 0))
  );

  IF v_apply_amount < 0.01 THEN
    RAISE EXCEPTION 'NOTHING_TO_APPLY: Invoice is already fully paid or amount is zero';
  END IF;

  -- Find AR account
  SELECT id INTO v_ar_account_id FROM chart_of_accounts
  WHERE company_id = p_company_id AND is_active = true
    AND (sub_type = 'accounts_receivable' OR account_name ILIKE '%receivable%' OR account_name ILIKE '%الذمم المدينة%')
  ORDER BY CASE WHEN sub_type = 'accounts_receivable' THEN 0 ELSE 1 END LIMIT 1;

  v_branch_id := v_invoice.branch_id;
  IF v_branch_id IS NULL THEN
    SELECT id INTO v_branch_id FROM branches
    WHERE company_id = p_company_id AND is_active = true
    ORDER BY is_main DESC NULLS LAST, name LIMIT 1;
  END IF;

  -- Create GL journal: Credit Applied (Dr AR credit-balance / Cr AR invoice)
  IF v_ar_account_id IS NOT NULL THEN
    INSERT INTO journal_entries (
      company_id, branch_id, reference_type, reference_id,
      entry_date, description, status
    ) VALUES (
      p_company_id, v_branch_id,
      'credit_applied', p_invoice_id::TEXT,
      CURRENT_DATE,
      'تطبيق رصيد دائن على الفاتورة ' || v_invoice.invoice_number,
      'draft'
    ) RETURNING id INTO v_journal_id;

    INSERT INTO journal_entry_lines (journal_entry_id, account_id, debit_amount, credit_amount, description)
    VALUES
      (v_journal_id, v_ar_account_id, v_apply_amount, 0, 'استهلاك رصيد دائن للعميل'),
      (v_journal_id, v_ar_account_id, 0, v_apply_amount, 'تسوية الذمم المدينة للفاتورة');

    UPDATE journal_entries SET status = 'posted' WHERE id = v_journal_id;
  END IF;

  -- Record in credit ledger (negative = consumption)
  INSERT INTO customer_credit_ledger (
    company_id, customer_id, source_type, source_id,
    journal_entry_id, amount, description, created_by
  ) VALUES (
    p_company_id, p_customer_id,
    'credit_applied', p_invoice_id,
    v_journal_id,
    -v_apply_amount,
    'تطبيق رصيد دائن على الفاتورة ' || v_invoice.invoice_number,
    p_user_id
  ) RETURNING id INTO v_credit_ledger_id;

  -- Update invoice paid_amount
  UPDATE invoices
  SET
    paid_amount = COALESCE(paid_amount, 0) + v_apply_amount,
    status = CASE
      WHEN COALESCE(paid_amount, 0) + v_apply_amount >= GREATEST(0, total_amount - COALESCE(returned_amount, 0))
      THEN 'paid'
      ELSE 'partially_paid'
    END,
    updated_at = NOW()
  WHERE id = p_invoice_id;

  RETURN jsonb_build_object(
    'success', true,
    'applied_amount', v_apply_amount,
    'journal_entry_id', v_journal_id,
    'credit_ledger_id', v_credit_ledger_id,
    'remaining_credit', v_available_credit - v_apply_amount
  );
END;
$$;

-- =============================================================================
-- SECTION 3: Atomic Payment Processing RPC
-- Single DB transaction: payment + AR/Revenue journal + invoice update
-- COGS is NOT included (too complex for SQL; handled by application layer)
-- =============================================================================
CREATE OR REPLACE FUNCTION public.process_invoice_payment_atomic(
  p_invoice_id       UUID,
  p_company_id       UUID,
  p_customer_id      UUID,
  p_amount           NUMERIC,
  p_payment_date     DATE,
  p_payment_method   TEXT,
  p_reference_number TEXT    DEFAULT NULL,
  p_notes            TEXT    DEFAULT NULL,
  p_account_id       UUID    DEFAULT NULL,
  p_branch_id        UUID    DEFAULT NULL,
  p_cost_center_id   UUID    DEFAULT NULL,
  p_warehouse_id     UUID    DEFAULT NULL,
  p_user_id          UUID    DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_invoice             RECORD;
  v_payment_id          UUID;
  v_ar_account_id       UUID;
  v_revenue_account_id  UUID;
  v_vat_account_id      UUID;
  v_shipping_account_id UUID;
  v_branch_id           UUID;
  v_invoice_journal_id  UUID;
  v_new_paid_amount     NUMERIC;
  v_new_status          TEXT;
  v_net_invoice_amount  NUMERIC;
BEGIN
  -- ✅ 1. Lock invoice row to prevent race conditions
  SELECT * INTO v_invoice
  FROM invoices
  WHERE id = p_invoice_id AND company_id = p_company_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'INVOICE_NOT_FOUND: Invoice % not found for company %',
      p_invoice_id, p_company_id;
  END IF;

  -- ✅ 2. Idempotency: prevent exact duplicate payments
  IF EXISTS (
    SELECT 1 FROM payments
    WHERE invoice_id        = p_invoice_id
      AND amount            = p_amount
      AND payment_date      = p_payment_date
      AND COALESCE(reference_number, '') = COALESCE(p_reference_number, '')
      AND COALESCE(is_deleted, false)    = false
  ) THEN
    RAISE EXCEPTION 'DUPLICATE_PAYMENT: A payment of % on % with reference [%] already exists for invoice %',
      p_amount, p_payment_date, COALESCE(p_reference_number, ''), p_invoice_id;
  END IF;

  -- ✅ 3. Resolve branch_id (invoice → company default)
  v_branch_id := COALESCE(p_branch_id, v_invoice.branch_id);
  IF v_branch_id IS NULL THEN
    SELECT id INTO v_branch_id
    FROM branches
    WHERE company_id = p_company_id AND is_active = true
    ORDER BY is_main DESC NULLS LAST, name
    LIMIT 1;
  END IF;
  IF v_branch_id IS NULL THEN
    RAISE EXCEPTION 'NO_BRANCH: No active branch found for company %. Create at least one branch.', p_company_id;
  END IF;

  -- ✅ 4. Resolve chart-of-accounts IDs
  SELECT id INTO v_ar_account_id
  FROM chart_of_accounts
  WHERE company_id = p_company_id AND is_active = true
    AND (
      sub_type     = 'accounts_receivable'
      OR account_name ILIKE '%receivable%'
      OR account_name ILIKE '%الذمم المدين%'
    )
  ORDER BY CASE WHEN sub_type = 'accounts_receivable' THEN 0 ELSE 1 END
  LIMIT 1;

  SELECT id INTO v_revenue_account_id
  FROM chart_of_accounts
  WHERE company_id = p_company_id AND is_active = true
    AND (
      sub_type     = 'sales_revenue'
      OR account_name ILIKE '%revenue%'
      OR account_name ILIKE '%المبيعات%'
      OR account_type = 'income'
    )
  ORDER BY
    CASE WHEN sub_type = 'sales_revenue' THEN 0 ELSE 1 END
  LIMIT 1;

  SELECT id INTO v_vat_account_id
  FROM chart_of_accounts
  WHERE company_id = p_company_id AND is_active = true
    AND (
      sub_type IN ('vat_output', 'tax_payable')
      OR account_name ILIKE '%ضريبة%'
      OR account_name ILIKE '%vat%'
    )
  LIMIT 1;

  -- ✅ 5. INSERT payment → trigger auto_create_payment_journal fires within THIS transaction
  --       → Cash/AR journal (Debit Cash / Credit AR) created atomically
  INSERT INTO payments (
    company_id, customer_id, invoice_id, payment_date, amount,
    payment_method, reference_number, notes, account_id,
    branch_id, cost_center_id, warehouse_id
  ) VALUES (
    p_company_id, p_customer_id, p_invoice_id, p_payment_date, p_amount,
    p_payment_method, p_reference_number,
    COALESCE(p_notes, 'دفعة على الفاتورة ' || v_invoice.invoice_number),
    p_account_id, v_branch_id, p_cost_center_id, p_warehouse_id
  ) RETURNING id INTO v_payment_id;

  -- ✅ 6. Create AR/Revenue journal on FIRST PAYMENT only (Cash Basis)
  --       Subsequent payments are covered by the Cash/AR journal from the trigger
  IF NOT EXISTS (
    SELECT 1 FROM journal_entries
    WHERE company_id     = p_company_id
      AND reference_type = 'invoice'
      AND reference_id   = p_invoice_id::TEXT
      AND (is_deleted IS NULL OR is_deleted = false)
      AND deleted_at IS NULL
  ) THEN
    IF v_ar_account_id IS NOT NULL AND v_revenue_account_id IS NOT NULL THEN
      -- Create as draft first (enforced by trg_posted_entry_lines_no_edit)
      INSERT INTO journal_entries (
        company_id, branch_id, reference_type, reference_id,
        entry_date, description, status, cost_center_id, warehouse_id
      ) VALUES (
        p_company_id, v_branch_id,
        'invoice', p_invoice_id::TEXT,
        COALESCE(v_invoice.invoice_date, p_payment_date),
        'فاتورة مبيعات ' || v_invoice.invoice_number,
        'draft',
        p_cost_center_id, p_warehouse_id
      ) RETURNING id INTO v_invoice_journal_id;

      -- Debit: AR = total invoice amount
      INSERT INTO journal_entry_lines (
        journal_entry_id, account_id, debit_amount, credit_amount, description, branch_id, cost_center_id
      ) VALUES (
        v_invoice_journal_id, v_ar_account_id,
        v_invoice.total_amount, 0,
        'الذمم المدينة (العملاء)',
        v_branch_id, p_cost_center_id
      );

      -- Credit: Revenue = subtotal
      INSERT INTO journal_entry_lines (
        journal_entry_id, account_id, debit_amount, credit_amount, description, branch_id, cost_center_id
      ) VALUES (
        v_invoice_journal_id, v_revenue_account_id,
        0, COALESCE(v_invoice.subtotal, v_invoice.total_amount),
        'إيراد المبيعات',
        v_branch_id, p_cost_center_id
      );

      -- Credit: VAT (conditional)
      IF v_vat_account_id IS NOT NULL AND COALESCE(v_invoice.tax_amount, 0) > 0.001 THEN
        INSERT INTO journal_entry_lines (
          journal_entry_id, account_id, debit_amount, credit_amount, description
        ) VALUES (
          v_invoice_journal_id, v_vat_account_id,
          0, v_invoice.tax_amount,
          'ضريبة القيمة المضافة المستحقة'
        );
      END IF;

      -- Credit: Shipping (conditional)
      IF COALESCE(v_invoice.shipping, 0) > 0.001 THEN
        SELECT id INTO v_shipping_account_id
        FROM chart_of_accounts
        WHERE company_id = p_company_id AND is_active = true
          AND (
            account_name ILIKE '%شحن%'
            OR account_name ILIKE '%بوسطة%'
            OR account_name ILIKE '%shipping%'
          )
        LIMIT 1;

        INSERT INTO journal_entry_lines (
          journal_entry_id, account_id, debit_amount, credit_amount, description
        ) VALUES (
          v_invoice_journal_id,
          COALESCE(v_shipping_account_id, v_revenue_account_id),
          0, v_invoice.shipping,
          'إيراد الشحن'
        );
      END IF;

      -- Post the journal (draft → posted pattern)
      UPDATE journal_entries
      SET status = 'posted'
      WHERE id = v_invoice_journal_id;
    END IF;
  END IF;

  -- ✅ 7. Calculate new paid amount and invoice status
  v_new_paid_amount := COALESCE(v_invoice.paid_amount, 0) + p_amount;

  -- Handle partially-returned invoices correctly
  v_net_invoice_amount := CASE
    WHEN COALESCE(v_invoice.returned_amount, 0) > 0
     AND v_invoice.total_amount < COALESCE(v_invoice.returned_amount, 0)
    THEN v_invoice.total_amount   -- total_amount already reduced (for 'sent' returns)
    ELSE GREATEST(0, v_invoice.total_amount - COALESCE(v_invoice.returned_amount, 0))
  END;

  v_new_status := CASE
    WHEN v_new_paid_amount >= v_net_invoice_amount THEN 'paid'
    ELSE 'partially_paid'
  END;

  -- ✅ 8. UPDATE invoice atomically (same transaction as payment + journals)
  UPDATE invoices
  SET
    paid_amount = v_new_paid_amount,
    status      = v_new_status,
    updated_at  = NOW()
  WHERE id = p_invoice_id;

  -- ✅ 9. Non-blocking audit log
  BEGIN
    INSERT INTO audit_logs (
      company_id, user_id, action, target_table,
      record_id, record_identifier, old_data, new_data
    ) VALUES (
      p_company_id, p_user_id, 'INSERT', 'payments',
      v_payment_id, v_invoice.invoice_number,
      jsonb_build_object(
        'status', v_invoice.status,
        'paid_amount', v_invoice.paid_amount
      ),
      jsonb_build_object(
        'status', v_new_status,
        'paid_amount', v_new_paid_amount,
        'payment_amount', p_amount,
        'payment_id', v_payment_id,
        'invoice_journal_created', v_invoice_journal_id IS NOT NULL
      )
    );
  EXCEPTION WHEN OTHERS THEN
    NULL; -- Non-fatal: audit failure must not block financial operation
  END;

  -- ✅ 10. Return structured result
  RETURN jsonb_build_object(
    'success',                 true,
    'payment_id',              v_payment_id,
    'new_paid_amount',         v_new_paid_amount,
    'new_status',              v_new_status,
    'net_invoice_amount',      v_net_invoice_amount,
    'remaining',               GREATEST(0, v_net_invoice_amount - v_new_paid_amount),
    'invoice_journal_created', v_invoice_journal_id IS NOT NULL
  );
END;
$$;

COMMENT ON FUNCTION public.process_invoice_payment_atomic IS
  'معالجة دفعة الفاتورة بشكل ذري (Atomic): '
  'INSERT payment + trigger (Cash/AR journal) + AR/Revenue journal + UPDATE invoice '
  'في معاملة DB واحدة. أي فشل = ROLLBACK كامل. '
  'COGS يُعالج لاحقًا بواسطة طبقة التطبيق (حساب FIFO معقد).';

-- Grant execute to authenticated role (RLS on underlying tables handles fine-grained access)
GRANT EXECUTE ON FUNCTION public.process_invoice_payment_atomic TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_customer_credit_balance TO authenticated;
GRANT EXECUTE ON FUNCTION public.apply_customer_credit_to_invoice TO authenticated;
