-- v3.58.4 Batch 1: Reports family page guides (18 pages)
-- =====================================================================
-- Adds 18 new page guides for the reports family. After this migration
-- the knowledge base grows from 42 -> 60 active guides.
-- See migration 20260528000400 for the Arabic FTS normalization that
-- makes these guides reliably searchable.
-- =====================================================================

INSERT INTO public.page_guides
  (page_key, title_ar, title_en, description_ar, description_en, steps_ar, steps_en, tips_ar, tips_en, is_active)
VALUES
('aging_ar',
 'تقرير أعمار الديون للعملاء',
 'Accounts Receivable Aging',
 'يعرض التقرير المبالغ المُستَحَقَّة من كل عميل مُصَنَّفَة حسب فترة التَأَخُّر (0-30 يوم، 31-60، 61-90، أكثر من 90). يُستَخدَم لمُتابَعَة الذمم المَدينة وأَولوية التَحصيل.',
 'Shows outstanding receivables grouped by overdue period (0-30, 31-60, 61-90, 90+ days). Used to prioritize collections and monitor customer debt.',
 '["اختر تاريخ الإسناد لحساب الأعمار", "صفِّ النَتائج حسب الفَرع أو العميل عند الحاجة", "صَدِّر التقرير PDF أو Excel للمراجعة", "تَواصل مع العملاء ذوى الأَعمار المُتَأَخِّرَة"]'::jsonb,
 '["Pick the as-of date for aging calculation", "Filter by branch or customer if needed", "Export to PDF or Excel for review", "Reach out to customers with overdue balances"]'::jsonb,
 ARRAY['الفَواتير المُحَوَّلَة بعَملات أَجنبية تَظهر بقيمة العملة الأَساسية حسب سعر اليوم', 'الأَعمار > 90 يوم تحتاج إجراءاً فورياً']::text[],
 ARRAY['Foreign-currency invoices appear in base currency at today rate', 'Receivables over 90 days need immediate action']::text[],
 TRUE),
('aging_ap',
 'تقرير أعمار الديون للموردين',
 'Accounts Payable Aging',
 'يَعرض المبالغ المُستَحَقَّة لكل مورد مُصَنَّفَة حسب فترة التَأخُّر. يُساعد على تَخطيط المدفوعات والاستفادة من خصومات الدفع المُبَكِّر.',
 'Shows outstanding payables grouped by overdue period. Helps plan payments and capture early-payment discounts.',
 '["اختر تاريخ الإسناد", "راجع المورِّدين الأكثر استحقاقاً", "خطِّط دفعات الفترة القادمة", "صَدِّر إن كنت تَحتاج تَوقيعات اعتماد"]'::jsonb,
 '["Pick the as-of date", "Review top creditors", "Plan upcoming payments", "Export for approval signatures"]'::jsonb,
 ARRAY['الدفعات المُبَكِّرَة قد تَحصل على خصم — راجع شروط كل مورد', 'الالتزامات > 60 يوم تَضر بعَلاقَتك مع المورد']::text[],
 ARRAY['Early payment may qualify for discounts — check vendor terms', 'Liabilities over 60 days harm vendor relationships']::text[],
 TRUE),
('cash_flow', 'قائمة التدفقات النقدية', 'Cash Flow Statement',
 'تقرير يَعرض حَركَة النقد (الداخل والخارج) خلال فترة مُحَدَّدَة، مُقَسَّم لـ تَدفقات تشغيلية، استثمارية، تمويلية.',
 'Shows cash inflows and outflows over a period, classified into operating, investing, and financing activities.',
 '["اختر الفترة الزمنية", "حدِّد الفَرع إذا أردت", "راجع التَدفُّق التشغيلى أولاً", "قارن مع الفترات السابقة للاتجاهات"]'::jsonb,
 '["Select the time period", "Optionally filter by branch", "Review operating cash flow first", "Compare to prior periods for trends"]'::jsonb,
 ARRAY['التَدفُّق التشغيلى السالب لفترات طويلة مؤشر تحذير', 'الاستهلاك ليس تدفُّق نقدى فعلى — يُضاف عكسياً']::text[],
 ARRAY['Negative operating cash flow for long periods is a warning sign', 'Depreciation is non-cash — added back']::text[],
 TRUE),
('cost_center_reports', 'تقارير مراكز التكلفة', 'Cost Center Reports',
 'تَحليل الإِيرادات والمَصروفات لكل مركز تكلفة، مُقارَنَة بين الفُروع، وأَداء كل وَحدَة تشغيلية.',
 'Analyzes revenues and expenses per cost center, compares branches, and shows operational unit performance.',
 '["اختر مَركَز التكلفة أو الفَرع المُراد", "حدِّد فترة المُقارَنَة", "راجع المَصاريف الأَعلى فى كل مَركَز", "قارِن النَتائج عبر الفُروع لاكتشاف الفُروق"]'::jsonb,
 '["Pick the cost center or branch", "Set the comparison period", "Review top expenses per center", "Compare across branches to spot variance"]'::jsonb,
 ARRAY['تأكَّد أن كل قَيد مُحاسبى لديه cost_center_id قبل الاعتماد على التقرير', 'الفُروق الكبيرة بين الفُروع تَستحق التَحقيق']::text[],
 ARRAY['Make sure every journal entry has cost_center_id before relying on this report', 'Large variance between branches warrants investigation']::text[],
 TRUE),
('daily_payments_receipts', 'التحصيلات والمدفوعات اليومية', 'Daily Payments & Receipts',
 'تقرير يَعرض كل التَحصيلات (المُستَلَمَة من العملاء) والمدفوعات (المَدفوعة للموردين) فى يوم مُحَدَّد أو فترة قصيرة. مَرجع يومى للخَزينة.',
 'Lists all daily collections from customers and payments to vendors. A daily reference for cashier reconciliation.',
 '["اختر التاريخ المَطلوب", "صفِّ بنوع المعاملة", "طابِق المجاميع مع رصيد الخزينة الفعلى", "صَدِّر للمراجعة اليومية"]'::jsonb,
 '["Pick the target date", "Filter by transaction type", "Reconcile totals against actual cash balance", "Export for daily review"]'::jsonb,
 ARRAY['أى فَرق بين التقرير والخزينة الفعلى يَستحق تَحقيقاً فورياً', 'الدفعات بعملات مُختَلفة تَظهر بالعملة الأَصلية + العملة الأَساسية']::text[],
 ARRAY['Any gap between the report and physical cash needs immediate investigation', 'Multi-currency payments show original + base currency']::text[],
 TRUE),
('dashboard_reports', 'تقارير لوحة التحكم', 'Dashboard Reports',
 'مَجموعة التقارير التَفاعلية على لَوحَة التَحَكُّم: المَبيعات اليومية، أَفضل العملاء، أَكثر المُنتَجات مَبيعاً، ومُلَخَّصات سريعة.',
 'Interactive dashboard reports: daily sales, top customers, best-selling products, and quick summaries.',
 '["اختر الفَتْرَة الزمنية", "راجع KPIs الرَئيسية فى الأَعلى", "تَفاعَل مع الرُسوم البَيانية للتَفاصيل", "قارِن مع نَفس الفَتْرَة من العام السابق"]'::jsonb,
 '["Pick the time period", "Review top-line KPIs", "Drill into charts for details", "Compare to same period last year"]'::jsonb,
 ARRAY['البيانات تُحَدَّث كل دقيقة تَقريباً', 'أَى KPI أَحمر يَستحق فَتح صفحة تَفصيلية']::text[],
 ARRAY['Data refreshes roughly every minute', 'Any red KPI deserves a detail drill-down']::text[],
 TRUE),
('equity_changes', 'قائمة تغيرات حقوق الملكية', 'Statement of Changes in Equity',
 'تَوضِح حَركَة حُقوق الملكية خلال الفترة: الأَرباح المُحتَجَزَة، السَحوبات، التَوزيعات، والاضافات الرأسمالية.',
 'Shows movement in equity over the period: retained earnings, drawings, distributions, and capital additions.',
 '["اختر السنة المالية أَو الفَتْرَة", "راجع رصيد بداية المُدَّة لكل بَند", "تَأَكَّد من تَوزيع الأَرباح فى نهاية السنة", "وَقِّع التقرير قبل الإِغلاق السَنوى"]'::jsonb,
 '["Select the fiscal period", "Review opening balance per item", "Verify year-end profit distribution", "Sign off before annual close"]'::jsonb,
 ARRAY['أَى تَعديل لفترات سابقة يَظهر فى صَف مُنفصِل', 'لا يَكتمل الإِقفال السَنوى إلا بعد توقيع هذا التقرير']::text[],
 ARRAY['Prior period adjustments appear on a separate line', 'Annual close is not complete without signing this report']::text[],
 TRUE),
('financial_trace_reports', 'التَتَبُّع المالى', 'Financial Trace Reports',
 'أَدوات استكشاف تَفصيلية للمُحاسبين: تَتَبُّع كل قَيد فى الشَجَرَة المُحاسبية، إِعادَة احتساب الأَرصدة، وفُحوصات التَكامُل المالى.',
 'Forensic tools for accountants: trace every journal entry, recompute balances, and run financial integrity checks.',
 '["استخدم Trace Explorer لمُتابَعَة قَيد مُحَدَّد", "شَغِّل Integrity Checks دورياً", "راجع تَقرير الـ Replay عند الشَك", "أَبلغ المُحاسب الرئيسى عن أَى فَرق"]'::jsonb,
 '["Use Trace Explorer to follow a specific entry", "Run Integrity Checks periodically", "Review the Replay report when in doubt", "Notify the lead accountant of any discrepancy"]'::jsonb,
 ARRAY['هذه أَدوات للخبراء فقط — أَى تَدَخُّل بدون فَهم قد يَكسر التَكامُل', 'احتفظ بـ backup قبل أَى عَمَلية إِصلاح']::text[],
 ARRAY['Expert-only tools — uninformed changes can break integrity', 'Keep a backup before any repair operation']::text[],
 TRUE),
('inventory_reports', 'تقارير المخزون', 'Inventory Reports',
 'مَجموعة تقارير المخزون: التَدقيق، الجرد، التَقييم، ومخزون كل مَخزن.',
 'Inventory toolkit: audit, count, valuation, and per-warehouse stock.',
 '["اختر التقرير المُحَدَّد من القائمة", "حدِّد الفَتْرَة والمخزن", "راجع المُنتَجات ذات الحَركَة المُنخَفضة", "احرص على تَطابق التقرير مع الجرد الفعلى"]'::jsonb,
 '["Select the report from the list", "Set period and warehouse", "Review slow-moving items", "Reconcile against physical count"]'::jsonb,
 ARRAY['تقييم المخزون يَستخدم FIFO حسب إِعدادات الشركة', 'فُروق الجرد > 1% تَستَحِق تَحقيقاً']::text[],
 ARRAY['Valuation uses FIFO per company settings', 'Count variance over 1% warrants investigation']::text[],
 TRUE),
('product_reports', 'تقارير المنتجات', 'Product Reports',
 'أَداء المُنتَجات تَفصيلياً: المَبيعات حسب المُنتَج، أَقرب المُنتَجات للانتهاء، أَفضل المُنتَجات أَداءً.',
 'Detailed product performance: sales per product, near-expiry items, top performers.',
 '["اختر التقرير من القائمة", "حدِّد الفَتْرَة الزمنية", "راجع المُنتَجات الأَعلى ربحاً", "اتَّخذ قرار تَجديد المخزون"]'::jsonb,
 '["Pick the specific report", "Set the time period", "Review most profitable items", "Decide restock per item"]'::jsonb,
 ARRAY['ربحية المنتج تُحسَب من سعر البيع - تكلفة FIFO', 'تقرير الصلاحية حَيوى لمَنع الخَسائر']::text[],
 ARRAY['Product margin = price minus FIFO cost', 'Expiry report is vital to prevent waste']::text[],
 TRUE),
('purchase_reports', 'تقارير المشتريات', 'Purchase Reports',
 'تَحليل المُشتَريات: المُوَرِّدون الأكثر تَعامُلاً، أَوامر الشراء حسب الحالة، تَطَوُّر أَسعار الشراء عبر الزمن.',
 'Purchasing analytics: top vendors, PO status, price evolution over time.',
 '["اختر التقرير من القائمة", "حدِّد فَترة المُقارَنَة", "راجع تَطَوُّر أَسعار الشراء", "قارن بين الموردين قبل اتِّخاذ قرار الشراء"]'::jsonb,
 '["Pick the specific report", "Set comparison period", "Review price evolution", "Compare vendors before purchasing"]'::jsonb,
 ARRAY['تَزايُد سعر الشراء يَستحق فَتح مُحادَثَة مع المورد', 'الـ PO غير المُكتَمِلَة لفترة طويلة تَعنى مَشاكل تَنفيذ']::text[],
 ARRAY['Rising costs warrant a vendor conversation', 'Long-open POs indicate delivery issues']::text[],
 TRUE),
('sales_bonus_reports', 'تقارير حَوافز المَبيعات', 'Sales Bonuses Reports',
 'يَحسب الحَوافز للمَوظفين المُؤَهَّلين بناءً على أَهداف المَبيعات وقواعد العمولات.',
 'Computes employee bonuses based on sales targets and commission rules.',
 '["اختر فَتْرَة الحَساب", "تَأَكَّد من إِعدادات العمولات", "راجع التَفاصيل لكل موظف", "اعتمد قبل إِضافة الحَوافز فى كَشف الرَواتب"]'::jsonb,
 '["Set the calculation period", "Verify commission settings", "Review per-employee detail", "Approve before adding to payroll"]'::jsonb,
 ARRAY['الحَوافز لا تُحسَب إلا للفَواتير المُحَصَّلَة فعلياً', 'تَعديل قواعد العُمولات يُؤَثِّر على الفُترَة الحالية']::text[],
 ARRAY['Bonuses count only on collected invoices', 'Changing commission rules affects the current period']::text[],
 TRUE),
('sales_reports', 'تقارير المَبيعات', 'Sales Reports',
 'تَحليل شامل للمَبيعات: حسب العميل، المنتج، الفترة، الفَرع، أَو المَوظف.',
 'Comprehensive sales analytics: by customer, product, period, branch, or employee.',
 '["اختر بُعد التَحليل", "حدِّد الفترة وقارِن مع السابقة", "اكتشف أَفضل العملاء", "صَدِّر للاجتماعات الأسبوعية"]'::jsonb,
 '["Pick the analysis dimension", "Set the period and compare", "Spot top customers and best sellers", "Export for weekly meetings"]'::jsonb,
 ARRAY['المَبيعات المُلغاة تَنزِل من الإِجمالى تلقائياً', 'الخَصم يُؤَثِّر على هامش الربح، ليس فقط على الإِيراد']::text[],
 ARRAY['Cancelled sales are auto-removed', 'Discounts hit profit margin, not just revenue']::text[],
 TRUE),
('shipping_reports', 'تقارير الشحن', 'Shipping Reports',
 'تَفاصيل وتَكاليف الشَحن لكل فاتورة: شركة الشحن، رقم البوليصة، التَكلفة، المَوقع الحالى. مَرجع لتَتَبُّع الشحنات وإدارة العَلاقَة مع شركات الشحن.',
 'Shipping details and costs per invoice: carrier, waybill, cost, current location. Reference for tracking shipments and managing carriers.',
 '["اختر شركة الشحن أَو الفترة", "راجع التَكاليف لكل بوليصة", "تَتَبَّع الشحنات المُتَأَخِّرَة", "قارِن أَداء شركات الشحن"]'::jsonb,
 '["Pick the carrier or time period", "Review cost per waybill", "Track delayed shipments", "Compare carrier performance"]'::jsonb,
 ARRAY['شركات الشحن تُضاف وتُدار من إِعدادات الشحن (settings/shipping)', 'تَكلفة الشحن تَدخل ضمن تَكلفة المُنتَج المُسَلَّم']::text[],
 ARRAY['Carriers are managed in Settings -> Shipping', 'Shipping cost feeds into product landed cost']::text[],
 TRUE),
('simple_summary_reports', 'التقارير المُبَسَّطَة', 'Simple Summary Reports',
 'نَظرَة عامَّة وسريعة لأَهم المُؤَشِّرات: إِجمالى المَبيعات، المَصاريف، الرَبح، عدد العُملاء.',
 'Quick overview of key metrics: total sales, expenses, profit, customer count.',
 '["اختر الشَهر أو الفترة", "راجع الأَرقام الرَئيسية بنَظرَة واحدة", "اضغط على أَى رَقم للتَفاصيل", "صَدِّر PDF للاجتماعات"]'::jsonb,
 '["Pick the month or period", "Review key numbers at a glance", "Tap any number for details", "Export PDF for meetings"]'::jsonb,
 ARRAY['التقرير يُلَخِّص فقط — للتَفاصيل استخدم تقارير القوائم الرَئيسية', 'الأَرقام تَستَخدم العملة الأَساسية فقط']::text[],
 ARRAY['This report summarizes only', 'Numbers use base currency only']::text[],
 TRUE),
('supplier_price_comparison', 'مقارنة أَسعار الموردين', 'Supplier Price Comparison',
 'يَعرض أَسعار نَفس المُنتَج عبر مَوردين مُختَلفين لاختيار الأَفضل سعراً وجَودةً.',
 'Compares prices of the same product across multiple vendors.',
 '["اختر المُنتَج أَو فئة المُنتَجات", "راجع أَسعار كل مورد", "قارن مع الجَودة والشروط", "اتَّخذ قرار اختيار المورد"]'::jsonb,
 '["Select the product or category", "Review per-vendor prices", "Compare quality and terms", "Make vendor choice"]'::jsonb,
 ARRAY['السعر الأَدنى ليس دائماً الأَفضل — راجع شروط الدَفع وزَمن التوريد', 'بَعض المُوَرِّدين يُقَدِّمون خصومات على الكَمِّيَّات']::text[],
 ARRAY['Lowest price isn''t always best', 'Some vendors offer volume discounts']::text[],
 TRUE),
('update_account_balances', 'تحديث أرصدة الحسابات', 'Update Account Balances',
 'أَداة إِدارية لإِعادَة احتساب الأَرصدة المُجَمَّعَة من القُيود الفعلية.',
 'Admin tool to recalculate aggregate balances from actual journal entries.',
 '["شَغِّل الأَداة بَعد أَى إِصلاح يَدوى للقُيود", "راجع الحسابات التى تَغَيَّر رَصيدها", "تَأَكَّد من تَوازُن ميزان المُراجَعَة بَعدها", "احتفظ بـ snapshot قبل التَشغيل"]'::jsonb,
 '["Run after any manual journal repair", "Review accounts whose balance changed", "Confirm trial balance still balances", "Keep a snapshot before running"]'::jsonb,
 ARRAY['أَداة للمُحاسب الرَئيسى فقط', 'بَعد التَشغيل، ميزان المُراجَعَة يجب أَن يَتَوازَن صِفر']::text[],
 ARRAY['Lead-accountant tool only', 'After run, trial balance must net to zero']::text[],
 TRUE),
('vat_reports', 'تقارير ضريبة القيمة المُضافَة', 'VAT Reports',
 'مَجموعة تقارير ضريبية: ضريبة المخرَجات (مَبيعات)، ضريبة المُدخَلات (مُشتَريات).',
 'Tax report suite: output VAT (sales), input VAT (purchases).',
 '["اختر الفَتْرَة الضريبية", "راجع ضَريبة المخرَجات والمُدخَلات", "احتسب الفَرق المُستَحَق", "صَدِّر التقرير بصيغَة مَصلَحة الضَرائب"]'::jsonb,
 '["Pick the tax period", "Review output and input VAT", "Compute the net payable", "Export in tax authority format"]'::jsonb,
 ARRAY['الفَواتير بدون رَقم ضَريبى لا تُقبَل فى الإِقرار', 'الإِقرار المُتَأَخِّر يُؤَدِّى إِلى غَرامات']::text[],
 ARRAY['Invoices without tax IDs are rejected', 'Late filing triggers penalties']::text[],
 TRUE);

SELECT public.ai_reindex_page_guides() AS chunks_after_batch1;
