-- =====================================================================
-- v3.74.585 — Sales-bonus integrity: cleanup + auto-reversal guard
-- (applied to production via Supabase MCP on 2026-07-09; mirrored here)
--
-- Dashboard integrity scan (ic_bonus_invoice_orphan) flagged one
-- orphan: a 50.00 EGP pending commission for the service staff,
-- generated by completing test booking BKG-2026-00001 — whose entire
-- chain (booking, invoice INV-2026-00001, payments, JEs) was
-- hard-deleted in the owner-ordered full cleanup. user_bonuses was the
-- one table that cleanup missed. The bonus was never paid, never in a
-- payroll run, and has no accounting impact → hard-delete to match the
-- "as if it never existed" cleanup.
--
-- Prevention: when an invoice (or a booking) is deleted, its UNPAID
-- pending bonuses are auto-reversed (status='reversed' + reversed_at +
-- reason) so the integrity scan stays clean. PAID bonuses are left
-- un-reversed DELIBERATELY: a paid commission whose source document
-- disappeared is a real anomaly that SHOULD keep alerting until a
-- human resolves it through payroll correction.
-- =====================================================================

-- (1) cleanup: the single orphan test bonus
DELETE FROM public.user_bonuses
WHERE id = 'bc94334d-69c5-40fc-aa19-3a94b15025c5'
  AND paid_at IS NULL
  AND payroll_run_id IS NULL;

-- (2) guard: auto-reverse unpaid bonuses when their invoice is deleted
CREATE OR REPLACE FUNCTION public.reverse_bonuses_on_invoice_delete()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $$
BEGIN
  UPDATE public.user_bonuses
     SET status = 'reversed',
         reversed_at = NOW(),
         reversal_reason = COALESCE(reversal_reason, '') ||
           CASE WHEN COALESCE(reversal_reason,'') = '' THEN '' ELSE ' | ' END ||
           'عكس آلى: حُذفت الفاتورة المصدر ' || COALESCE(OLD.invoice_number, OLD.id::text),
         updated_at = NOW()
   WHERE invoice_id = OLD.id
     AND reversed_at IS NULL
     AND paid_at IS NULL
     AND payroll_run_id IS NULL;
  RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS bonuses_reverse_on_invoice_delete ON public.invoices;
CREATE TRIGGER bonuses_reverse_on_invoice_delete
BEFORE DELETE ON public.invoices
FOR EACH ROW EXECUTE FUNCTION public.reverse_bonuses_on_invoice_delete();

-- (3) same for booking-linked bonuses that never got an invoice
CREATE OR REPLACE FUNCTION public.reverse_bonuses_on_booking_delete()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO 'public'
AS $$
BEGIN
  UPDATE public.user_bonuses
     SET status = 'reversed',
         reversed_at = NOW(),
         reversal_reason = COALESCE(reversal_reason, '') ||
           CASE WHEN COALESCE(reversal_reason,'') = '' THEN '' ELSE ' | ' END ||
           'عكس آلى: حُذف الحجز المصدر ' || COALESCE(OLD.booking_no, OLD.id::text),
         updated_at = NOW()
   WHERE booking_id = OLD.id
     AND invoice_id IS NULL
     AND reversed_at IS NULL
     AND paid_at IS NULL
     AND payroll_run_id IS NULL;
  RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS bonuses_reverse_on_booking_delete ON public.bookings;
CREATE TRIGGER bonuses_reverse_on_booking_delete
BEFORE DELETE ON public.bookings
FOR EACH ROW EXECUTE FUNCTION public.reverse_bonuses_on_booking_delete();
